version: '2'

services:

  mongo:
    image: docker.io/bitnami/mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/bitnami/mongodb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_USERNAME=parse
      - MONGODB_DATABASE=parse
      - MONGODB_PASSWORD=parse

  parse:
    image: docker.io/bitnami/parse:5
    ports:
      - '1337:1337'
    volumes:
      - ./parse_data:/bitnami/parse
    depends_on:
      - mongo
    environment:
      - PARSE_DATABASE_HOST=mongo
      - PARSE_DATABASE_PORT_NUMBER=27017
      - PARSE_DATABASE_USER=parse
      - PARSE_DATABASE_NAME=parse
      - PARSE_DATABASE_PASSWORD=parse

volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local