version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=parse
      - MONGO_INITDB_ROOT_PASSWORD=parse

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: parse
      ME_CONFIG_MONGODB_ADMINPASSWORD: parse
      ME_CONFIG_MONGODB_URL: mongodb://parse:parse@mongo:27017/


#
#  parse:
#    image: docker.io/bitnami/parse:4
#    ports:
#      - '1337:1337'
#    volumes:
#      - './parse_data:/bitnami/parse'
#    depends_on:
#      - mongodb
#    environment:
#      - PARSE_DATABASE_HOST=mongodb
#      - PARSE_DATABASE_PORT_NUMBER=27017
#      - PARSE_DATABASE_USER=bn_parse
#      - PARSE_DATABASE_NAME=bitnami_parse
#      - PARSE_DATABASE_PASSWORD=bitnami123
#  parse-dashboard:
#    image: docker.io/bitnami/parse-dashboard:3
#    ports:
#      - '4040:4040'
#    volumes:
#      - './parse_dashboard_data:/bitnami'
#    depends_on:
#      - parse

volumes:
  mongo_data:
    driver: local
#  parse_data:
#    driver: local
#  parse_dashboard_data:
#    driver: local

networks:
  parse-network:
    driver: bridge